name: deploy_to_gcloud
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environ: ${{ steps.setvars.outputs.environ }}
      gprojectid: ${{ steps.setvars.outputs.gprojectid }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo '::set-output name=environ::prod'
            echo '::set-output name=gprojectid::gcp-wow-rwds-api-prod'
          elif [[ ${{ github.ref }} == 'refs/heads/hotfix' ]]; then
            echo '::set-output name=environ::prod'
            echo '::set-output name=gprojectid::gcp-wow-rwds-api-prod'
          elif [[ ${{ github.ref }} == 'refs/heads/release' ]]; then
            echo '::set-output name=environ::uat'
            echo '::set-output name=gprojectid::gcp-wow-rwds-api-uat'
          elif [[ ${{ github.ref }} == 'refs/heads/integrate' ]]; then
            echo '::set-output name=environ::test'
            echo '::set-output name=gprojectid::gcp-wow-rwds-api-test'
          elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
            echo '::set-output name=environ::dev'
            echo '::set-output name=gprojectid::gcp-wow-rwds-api-01-dev'
          else
            echo '::set-output name=environ::poc'
            echo '::set-output name=gprojectid::gcp-wow-rwds-api-poc-dev'
          fi
  test_build_and_package:
    # job test_build_and_package does following things
    # - checkout source code
    # - install node
    # - install dependencies
    # - run build (if applicable)
    # - run test
    # - upload artifacts
    runs-on: ubuntu-latest
    needs: init
    if: ${{ needs.init.outputs.environ }} != 'null'
    environment:
      name: ${{ needs.init.outputs.environ }}
    env:
      # generate domain name for vault secret
      VAULT_ADDR: https://vault.${{ needs.init.outputs.environ }}.gcp.api-wr.com:8200
    steps:
      - # simply checkout code
        # https://github.com/marketplace/actions/checkout#checkout-v2
        name: Checkout
        uses: actions/checkout@v2
      - name: check url
        run: |
          echo "${{ env.VAULT_ADDR }}"
      - # retrieve .npmrc from vault, hashicorp/vault-action@v2.1.2 is 3rd party action
        # https://github.com/marketplace/actions/vault-secrets
        name: Get npmrc from Vault
        id: vault
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          caCertificate: ${{ secrets.VAULT_CA }}
          secrets: |
            kv/data/apis/npmrc npmrc ;
        # run: |
        #   echo "${{ env.VAULT_ADDR }}" >>abc
        #   echo "${{ secrets.VAULT_TOKEN }} " >>abc
        #   echo "${{ secrets.VAULT_CA }} " >>abc
        #   cat abc
      - # setup node, install nodejs in runner
        # https://github.com/marketplace/actions/setup-node-js-environment
        #
        # TODO: upgrade to V2
        #
        name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - # setup node module caching, see:
        # https://github.com/marketplace/actions/cache
        #
        # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
        #
        name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.OS }}-node-
              ${{ runner.OS }}-
      - # install dependencies, using .npmrc if applicable
        # this one doesn't need predefined actions
        name: Install Dependencies
        run: |
          echo \$\{\{ steps.vault.outputs.npmrc \}\} \|base64 -d \> \.npmrc
          npm ci
      - # run unit test
        name: Run Unit Tests
        run: npm test
      - # run build
        name: Build
        run: npm run build
      - # bundle up contents and upload
        # https://github.com/marketplace/actions/upload-a-build-artifact
        #
        # This artifacts will be uploaded to github, and is visible in
        # workflow execution details page
        #
        name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: |
              dist
              ./package.json
              ./abc
              ./.npmrc

  # deploy_to_gcloud:
  #   runs-on: ubuntu-latest
  #   needs: init
  #   if: ${{ needs.init.outputs.environ }} != 'null'
  #   environment:
  #     name: ${{ needs.init.outputs.environ }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #     - run: |
  #         npm ci
  #     - run: |
  #         npm run build
  #     - id: create_env
  #       run: |
  #         cat <<EOM > env_kv.yml
  #         VAR_1: '1232'
  #         VAR_2: ABCA
  #         EOM
  #         cat ./env_kv.yml
  #     - # initialize gcloud sdk by using 3rd party action
  #       # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
  #       name: Set up Cloud SDK
  #       uses: google-github-actions/setup-gcloud@master
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_key: ${{ secrets.GCP_SA_KEY }}
  #         export_default_credentials: true
  #     - # run simple gcloud cli command to verify previous setup
  #       name: User gcloud CLI
  #       run: gcloud info
  #     - # deploy function to google cloud using 3rd party action
  #       # https://github.com/marketplace/actions/cloud-functions-deploy
  #       id: deploy
  #       name: deploy function
  #       uses: google-github-actions/deploy-cloud-functions@main
  #       with:
  #         name: hello_http
  #         runtime: nodejs12
  #         entry_point: say_hello
  #         memory_mb: 256
  #         region: us-central1
  #         env_vars_file: ./env_kv.yml
  #         # credentials: ${{ secrets.gcp_credentials }}
  #         source_dir: ./dist
  #         # project_id:
  #         description: hello http function
  #         # vpc_connector:
  #         # service_account_email: play-with-functions-303505@appspot.gserviceaccount.com
  #         timeout: 60
  #         max_instances: 10
  #         # event_trigger_type: http
  #     - id: dump
  #       name: dump deploy result
  #       run: |
  #         echo "${{ steps.deploy.outputs.url }}"
  #     - run: |
  #         echo "deploying to ${{ needs.init.outputs.environ }}"
  #         echo "project is ${{ needs.init.outputs.gprojectid }}"
  #     - run: |
  #         echo "something more to do"
